development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: funder_league_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: funder_league_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: funder_league_production
  pool: 5
